# Generated by Django 4.1.1 on 2024-05-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welearnApp', '0005_passwordreset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructorprofile',
            old_name='skill',
            new_name='dob',
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='bio_data',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
