# Generated by Django 4.1.1 on 2024-05-15 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welearnApp', '0006_rename_skill_instructorprofile_dob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('durtion', models.CharField(blank=True, choices=[('ONE', 'TWO WEEKS'), ('TWO', 'ONE MONTHS'), ('THREE', 'TWO MONTHS'), ('FOUR', 'THREE MONTHS'), ('FIVE', 'FOUR MONTHS'), ('SIX', 'FIVE MONTHS'), ('SEVEN', 'SIX MONTHS'), ('EIGHT', 'ONE YEAR'), ('NINE', 'TWO YEARS +')], max_length=255, null=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welearnApp.instructorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('time', models.TimeField()),
                ('class_booked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welearnApp.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welearnApp.studentprofile')),
            ],
        ),
    ]
