# Generated by Django 4.1.1 on 2024-05-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welearnApp', '0007_class_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='name',
            new_name='class_name',
        ),
        migrations.AlterField(
            model_name='class',
            name='durtion',
            field=models.CharField(blank=True, choices=[('ONE', 'TWO WEEKS'), ('TWO', 'ONE MONTHS'), ('THREE', 'TWO MONTHS'), ('FOUR', 'THREE MONTHS'), ('FIVE', 'FOUR MONTHS'), ('SIX', 'FIVE MONTHS'), ('SEVEN', 'SIX MONTHS'), ('EIGHT', 'ONE YEAR ABOVE')], max_length=255, null=True),
        ),
    ]
