# Generated by Django 4.1.1 on 2024-05-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welearnApp', '0008_rename_name_class_class_name_alter_class_durtion'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
