# Generated by Django 4.1.1 on 2024-05-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welearnApp', '0010_instructorprofile_is_hired_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
