# Generated by Django 5.0.6 on 2024-06-18 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welearnApp', '0012_studentprofile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='day',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
        migrations.AddField(
            model_name='booking',
            name='dayone',
            field=models.CharField(blank=True, choices=[('ONE', 'MONDAY'), ('TWO', 'TUESDAY'), ('THREE', 'WEDNESDAY'), ('FOUR', 'THURSDAY'), ('FIVE', 'FRIDAY'), ('SIX', 'SATURDAY')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='daythree',
            field=models.CharField(blank=True, choices=[('ONE', 'MONDAY'), ('TWO', 'TUESDAY'), ('THREE', 'WEDNESDAY'), ('FOUR', 'THURSDAY'), ('FIVE', 'FRIDAY'), ('SIX', 'SATURDAY')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='daytwo',
            field=models.CharField(blank=True, choices=[('ONE', 'MONDAY'), ('TWO', 'TUESDAY'), ('THREE', 'WEDNESDAY'), ('FOUR', 'THURSDAY'), ('FIVE', 'FRIDAY'), ('SIX', 'SATURDAY')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='timeone',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='timethree',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='timetwo',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiredInstructors', to='welearnApp.studentprofile'),
        ),
    ]
