# Generated by Django 5.0.6 on 2024-06-21 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welearnApp', '0014_remark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remark',
            old_name='comment',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='remark',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='remark',
            name='sender',
        ),
        migrations.AddField(
            model_name='remark',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='welearnApp.class'),
        ),
        migrations.AddField(
            model_name='remark',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remark',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_remarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remark',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_remarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
