# Generated by Django 5.0.6 on 2024-06-21 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welearnApp', '0015_rename_comment_remark_text_remove_remark_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remark',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_remarks', to='welearnApp.studentprofile'),
        ),
        migrations.AlterField(
            model_name='remark',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_remarks', to='welearnApp.instructorprofile'),
        ),
    ]
