# Generated by Django 5.0.6 on 2024-06-21 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welearnApp', '0016_alter_remark_student_alter_remark_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remark',
            name='course',
        ),
        migrations.RemoveField(
            model_name='remark',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='remark',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='remark',
            name='student',
        ),
        migrations.RemoveField(
            model_name='remark',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='remark',
            name='text',
        ),
        migrations.AddField(
            model_name='remark',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remark',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remark',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remark',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
