# Generated by Django 5.0.6 on 2024-08-27 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welearnApp', '0018_instructorremark_studentremark_delete_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='dayone',
            field=models.CharField(blank=True, choices=[('MONDAY', 'MONDAY'), ('TUESDAY', 'TUESDAY'), ('WEDNESDAY', 'WEDNESDAY'), ('THURSDAY', 'THURSDAY'), ('FRIDAY', 'FRIDAY'), ('SATURDAY', 'SATURDAY')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='daythree',
            field=models.CharField(blank=True, choices=[('MONDAY', 'MONDAY'), ('TUESDAY', 'TUESDAY'), ('WEDNESDAY', 'WEDNESDAY'), ('THURSDAY', 'THURSDAY'), ('FRIDAY', 'FRIDAY'), ('SATURDAY', 'SATURDAY')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='daytwo',
            field=models.CharField(blank=True, choices=[('MONDAY', 'MONDAY'), ('TUESDAY', 'TUESDAY'), ('WEDNESDAY', 'WEDNESDAY'), ('THURSDAY', 'THURSDAY'), ('FRIDAY', 'FRIDAY'), ('SATURDAY', 'SATURDAY')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='durtion',
            field=models.CharField(blank=True, choices=[('TWO WEEKS', 'TWO WEEKS'), ('ONE MONTHS', 'ONE MONTHS'), ('TWO MONTHS', 'TWO MONTHS'), ('THREE MONTHS', 'THREE MONTHS'), ('FOUR MONTHS', 'FOUR MONTHS'), ('FIVE MONTHS', 'FIVE MONTHS'), ('SIX MONTHS', 'SIX MONTHS'), ('ONE YEAR ABOVE', 'ONE YEAR ABOVE')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='welearnApp.instructorprofile'),
        ),
        migrations.AlterField(
            model_name='studentremark',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='welearnApp.instructorprofile'),
        ),
        migrations.AlterField(
            model_name='studentremark',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentRemark', to='welearnApp.studentprofile'),
        ),
    ]
