# Generated by Django 5.0.6 on 2024-08-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welearnApp', '0019_alter_booking_dayone_alter_booking_daythree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='timeone',
            field=models.CharField(blank=True, choices=[('10am-12pm', '10am-12pm'), ('12pm-2pm', '12pm-2pm'), ('2pm-4pm', '2pm-4pm'), ('4pm-6pm', '4pm-6pm')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='timethree',
            field=models.CharField(blank=True, choices=[('10am-12pm', '10am-12pm'), ('12pm-2pm', '12pm-2pm'), ('2pm-4pm', '2pm-4pm'), ('4pm-6pm', '4pm-6pm')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='timetwo',
            field=models.CharField(blank=True, choices=[('10am-12pm', '10am-12pm'), ('12pm-2pm', '12pm-2pm'), ('2pm-4pm', '2pm-4pm'), ('4pm-6pm', '4pm-6pm')], max_length=255, null=True),
        ),
    ]
