# Generated by Django 5.0.6 on 2024-08-27 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welearnApp', '0020_alter_booking_timeone_alter_booking_timethree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allBookings', to='welearnApp.instructorprofile'),
        ),
    ]
