# Generated by Django 5.0.6 on 2024-08-30 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welearnApp', '0021_booking_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSuccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPaymentSuccessful', models.BooleanField(default=False)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='isPayed', to='welearnApp.booking')),
            ],
        ),
    ]
