# Generated by Django 5.0.6 on 2024-08-30 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welearnApp', '0022_paymentsuccess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='durtion',
            new_name='duration',
        ),
    ]
