# Generated by Django 5.0.6 on 2024-09-03 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welearnApp', '0023_rename_durtion_class_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsuccess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentsuccess',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='welearnApp.studentprofile'),
        ),
    ]
