# Generated by Django 5.0.6 on 2024-09-04 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welearnApp', '0024_paymentsuccess_created_at_paymentsuccess_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentsuccess',
            name='student',
        ),
    ]
