# Generated by Django 5.0.6 on 2024-09-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welearnApp', '0025_remove_paymentsuccess_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
