# Generated by Django 5.0.6 on 2024-09-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welearnApp', '0026_user_otp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='LGA',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='years_of_experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_secret',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
