# Generated by Django 5.0.6 on 2024-09-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welearnApp', '0027_instructorprofile_lga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
