# Generated by Django 5.0.6 on 2024-09-06 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welearnApp', '0028_instructorprofile_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSeeRemarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Instructor', 'Instructor'), ('Student', 'Student'), ('Admin', 'Admin')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instructorremark',
            name='admin_remark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructorAdminRemark', to='welearnApp.adminseeremarks'),
        ),
        migrations.AddField(
            model_name='studentremark',
            name='admin_remark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentAdminRemark', to='welearnApp.adminseeremarks'),
        ),
    ]
